import { Inter } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import Hero from "@/components/common/hero";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Patriots",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar /> */}
        <Hero />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
